# nixpacks.toml
[build]
# Backend: Specify how to build the backend
[[phases]]
name = "build-backend"
directory = "Backend"
cmds = ["npm install", "npm run build"]

# Frontend: Specify how to build the frontend
[[phases]]
name = "build-frontend"
directory = "Frontend/frontend"
cmds = ["npm install", "npm run build"]

[run]
# Backend: Run backend service
[[services]]
name = "backend"
start = "cd Backend && npm run start"

# Frontend: Run frontend service (serve the built frontend)
[[services]]
name = "frontend"
start = "cd Frontend/frontend && npm run start"
